.PHONY: clean All

All:
	@echo "----------Building project:[ Challenge-global - Debug ]----------"
	@cd "Challenge-global" && "$(MAKE)" -f  "Challenge-global.mk"
clean:
	@echo "----------Cleaning project:[ Challenge-global - Debug ]----------"
	@cd "Challenge-global" && "$(MAKE)" -f  "Challenge-global.mk" clean
