.PHONY: clean All

All:
	@echo "----------Building project:[ Challenge-member - Debug ]----------"
	@cd "Challenge-member" && "$(MAKE)" -f  "Challenge-member.mk"
clean:
	@echo "----------Cleaning project:[ Challenge-member - Debug ]----------"
	@cd "Challenge-member" && "$(MAKE)" -f  "Challenge-member.mk" clean
